### PR TITLE
fixing clear method in element actions

### PR DESCRIPTION
**Pull request by zanoon2020**
Dear @MohabMohie , for your recommendations , i commented the part of clearing using selenium native method and only left clearing using back space .

### CODE REVIEW

**Comment by MahmoudElSharkawy** [comment]
@zanoon2020 we have an issue related to the change.
I want to ask please; Why are we doing this change?, what's wrong with the Selenium clear method?
image

**Comment by zanoon2020** [comment]
> @zanoon2020 we have an issue related to the change.
> I want to ask please; Why are we doing this change?, what's wrong with the Selenium clear method?
> image
> 

@MahmoudElSharkawy with some angular input elements this method cause type method to type only 1 string , we investigated and found the issue in selenium clear method , in shaft we are clearing the field by default before type although we have flag for clearing before typing , why we have the flag if we are trying to clear first anyway , so i commented the part that clearing any way and left the related part to the flag as suggestion not final solution .

**Comment by MahmoudElSharkawy** [comment]
> > @zanoon2020 we have an issue related to the change.
> > I want to ask please; Why are we doing this change?, what's wrong with the Selenium clear method?
> > image
> 
> @MahmoudElSharkawy with some angular input elements this method cause type method to type only 1 string in firefox , we investigated and found the issue in selenium clear method , in shaft we are clearing the field by default before type although we have flag for clearing before typing , why we have the flag if we are trying to clear first anyway , so i commented the part that clearing any way and left the related part to the flag as suggestion not final solution .

@zanoon2020  Can't we just move the flag?

**Comment by zanoon2020** [comment]
@MahmoudElSharkawy the method first clearing using default clear method the trying to clear letter by letter using back space , we will need to update the logic if clearing using clear method pass then not to try clearing letter by letter , but the question is why we should have two methods to clear the element of one of them is working 100%

**Comment by zanoon2020** [comment]
@MahmoudElSharkawy the method first clearing using default clear method the trying to clear letter by letter using back space , we will need to update the logic if clearing using clear method pass then not to try clearing letter by letter , but the question is why we should have two methods to clear the element of one of them is working 100%

**Comment by zanoon2020** [comment]
@MahmoudElSharkawy i have another solution, to call shaft clear method from element actions , but didn't know how to 😁.anf if the flag is enabled. Then clear logic will be applied

**Comment by zanoon2020** [comment]
@MahmoudElSharkawy i see all E2E tests pass , how can i get to the failed one , is it from my pull request ?

**Comment by MahmoudElSharkawy** [comment]
> @MahmoudElSharkawy i see all E2E tests pass , how can i get to the failed one , is it from my pull request ?

yes, check the triggered cases from your PR. I just created a new PR and it's passing.

**Comment by MahmoudElSharkawy** [comment]
@zanoon2020 
Can't we just have it like this
```
If(clearBeforeTyping) {
    if(backSpaceMethod) {
      // backspace login
    } else {
          // use clear method
           }
}
```

**Comment by zanoon2020** [comment]
@MahmoudElSharkawy the issue because type method was clearing first before typing By default and the flag was only for clearing using backspace , there is 2 solutions for this , one to set the clearing using backspace flag default value to true , second to fix the method clearing before typing itself ,

**Comment by zanoon2020** [comment]
> @zanoon2020 Can't we just have it like this
> 
> ```
> If(clearBeforeTyping) {
>     if(backSpaceMethod) {
>       // use backspace method
>     } else {
>           // use clear method
>      }
> }
> ```
we have one flag attemptClearBeforeTypingUsingBackspace , and the typing method always to clear first

**Comment by zanoon2020** [comment]
@MahmoudElSharkawy let us take step back , is correct behavior for type method is trying to clear first by default ? or it's optional

**Comment by MahmoudElSharkawy** [comment]
> @MahmoudElSharkawy let us take step back , is correct behavior for type method is trying to clear first by default ? or it's optional

It should be optional and enabled by default in the properties.

**Comment by zanoon2020** [comment]
> > @MahmoudElSharkawy let us take step back , is correct behavior for type method is trying to clear first by default ? or it's optional
> 
> It should be optional and enabled by default in the properties.

exactly , tests failed because it's done hard coded and the default value of  flag is false 
image

**Comment by MahmoudElSharkawy** [comment]
@zanoon2020 
let's do the flag then :D

**Pull request closed without merging**
