### PR TITLE
Remote server connection issue

### PR DESCRIPTION
**Pull request by MohabMohie**

### CODE REVIEW

**Comment by MohabMohie** [comment]
One push remaining... The only scenario I didn't test didn't pass

**Comment by MohabMohie** [comment]
@MahmoudElSharkawy I would merge and release with a known issue that blocks Mac until we release a fix in a couple of days.
Thoughts?

**Comment by MahmoudElSharkawy** [comment]
> @MahmoudElSharkawy I would merge and release with a known issue that blocks Mac until we release a fix in a couple of days. Thoughts?

@MohabMohie Just checked and everything seems fine except for the Mac. 
Ok, let's go for it and share the issue.

**Comment by MohabMohie** [comment]
> > @MahmoudElSharkawy I would merge and release with a known issue that blocks Mac until we release a fix in a couple of days. Thoughts?
> 
> @MohabMohie Just checked and everything seems fine except for the Mac. Ok, let's go for it and share the issue.

Your call. PR won't be merged unless you approve the review.

**Review by MahmoudElSharkawy — APPROVED** [review]

**Pull request merged**
