### PR TITLE
Open Execution Summary Report After Execution

### PR DESCRIPTION
**Pull request by MahmoudElSharkawy**

### CODE REVIEW

**Comment by MahmoudElSharkawy** [comment]
> Don't forget to add to the flags class and the configuration manager please.
> 
> I also think we should disable allure by default and keep this one enabled by default, which also requires changes in the default properties file, flags class, and configuration manager

Done :D

**Review by MohabMohie — APPROVED** [review]

**Comment by MohabMohie** [comment]
Looking good 👍
Let's check the tests, also I recommend upgrading the e2etests pipeline to upload the allure and summary, since we're disabling extent by default now...

**Comment by MahmoudElSharkawy** [comment]
> Looking good 👍 Let's check the tests, also I recommend upgrading the e2etests pipeline to upload the allure and summary, since we're disabling extent by default now...

Done :D

**Review by MohabMohie — APPROVED** [review]
👌

**Pull request merged**
