### PR TITLE
907 bug firefox showing several console warnings and issues and not maximizable with the latest engine version

### PR DESCRIPTION
**Pull request by MohabMohie**

### CODE REVIEW

**Comment by MohabMohie** [comment]
@MahmoudElSharkawy please don't merge, I'll reopen tomorrow

**Comment by blacelle** [comment]
@MohabMohie I hope it is clear how to disable OpenRewrite in CleanThat.

**Comment by MohabMohie** [comment]
> @MohabMohie I hope it is clear how to disable OpenRewrite in CleanThat.

I thought it was, but maybe I misunderstood something. I dialed the engine letter as well, would you kindly double check?

**Comment by blacelle** [comment]
I see you disabled the step 4h ago, and the whole engine a few minutes ago. It made me feel you encounter an oissue with step disabling, but the code looks on my side.

However, the issue now is different: Cleanthat will not revert the changes by itself. However, now the step/engine is disabled, it will not re-apply its (faulty) changes. 

Please, revert the code manually (i.e revert the unsatisfactory part). This time, Cleanthat will not re-apply its (faulty) magic.

**Comment by MohabMohie** [comment]
> I see you disabled the step 4h ago, and the whole engine a few minutes ago. It made me feel you encounter an oissue with step disabling, but the code looks OK on my side.
> 
> However, the issue now is different: Cleanthat will not revert the changes by itself. However, now the step/engine is disabled (and merged in this branch), it will not re-apply its (faulty) changes.
> 
> Please, revert the code manually (i.e revert the unsatisfactory part). This time, Cleanthat will not re-apply its (faulty) magic.

Yes I did that for the broken switch case lambda upgrade, but I found that it had also changed a package name in one of my test classes from "testPackage" to "testpackage" without refactoring the actual package, which was also breaking some tests.

I fixed that file and will allow the pipelines to run again now.

**Comment by MohabMohie** [comment]
@MahmoudElSharkawy finally good to go, kindly review and merge.

Next. Time I will keep the PR drafted until it's actually ready.

**Comment by MohabMohie** [comment]
Apologies, I keep causing conflicts with myself... still getting used to smaller PRs and faster branch cycle time... now I have to merge this PR so that you'll actually be able to see the other one.

**Pull request merged**
