### PR TITLE
fix issue with the least changes possible

### PR DESCRIPTION
**Pull request by MohabMohie**
- migrate to standard browser naming for firefox, chrome, safari, ie, and edge
- remove unsupported argument "-foreground" for firefox
- enable BiDi use with firefox
- fix auto-maximize condition to work for both Browser.FIREFOX.getName(); and "MozillaFirefox"

### CODE REVIEW

**Comment by blacelle** [comment]
@MohabMohie Please skip openrewrite in https://github.com/ShaftHQ/SHAFT_ENGINE/blob/master/.cleanthat/cleanthat.yaml#L23, switching the skip flag to true.

This engine seems to behave badly in your case. I'll work into this.

**Comment by MohabMohie** [comment]
> @MohabMohie Please skip openrewrite in https://github.com/ShaftHQ/SHAFT_ENGINE/blob/master/.cleanthat/cleanthat.yaml#L23, switching the skip flag to true.
> 
> This engine seems to behave badly in your case. I'll work into this. Very sorry for the inconvenience.

THANK YOU :D it's been bugging me all day... I thought it was something I did...

**Comment by blacelle** [comment]
I'll open later another PR with an improved configuration for your project. OpenRewrite is quite recent in CleanThat, and it is failing producing correct code in this case.

**Comment by MohabMohie** [comment]
I guess that's because of the old switch case syntax and the new lambda one... I've also spotted a couple of commented nulls that are probably worth investigating.

Either way, I really appreciate your support!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
