### PR TITLE
Create configurable Page Source attachment for WebDriver

### PR DESCRIPTION
**Pull request by MahmoudElSharkawy**
* Created new page Source section in the configurations manager
* New whenToTakePageSourceSnapshot property in the VisualValidations.properties and dded them to the visuals class 

image
image

### CODE REVIEW

**Review by MohabMohie — CHANGES_REQUESTED** [review]
Can we set the default to never please?
Similar to the gif, this feature will have negative performance impact on the whole test run, so it makes sense to be disabled by default at least at first.

If you agree, please implement it and feel free to merge.

If not let's discuss with the TLC

**Comment by MahmoudElSharkawy** [comment]
@MohabMohie I pushed some code enhancements to make it performance efficient (it wont take the snapshot unless it have to based on the configurations)..
Please check again and tell me if you have any more concerns.

**Comment by MohabMohie** [comment]
I understand, but still an extra WebDriver call on the long run will have negative performance impact.
I'm fine with the implementation itself, I just think it should be disabled by default.

**Review by MohabMohie — APPROVED** [review]
Your call Mahmoud :)

**Pull request merged**
